---
builds:
  - id: verify-conformance
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"

defaultPlatforms:
  - linux/amd64
