---
steps:
  # NOTE this image comes with Go which may
  #      end up not matching the version required
  #      in go.mod
  - name: ghcr.io/ko-build/ko:v0.16.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        export KO_DOCKER_REPO=gcr.io/$PROJECT_ID/verify-conformance
        ko build --bare --tags $_GIT_TAG .
  # TODO sign image with OIDC
  #      https://docs.sigstore.dev/signing/overview/#on-google-cloud-platform
substitutions:
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'main'
options:
  substitution_option: 'ALLOW_LOOSE'
