---
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: verify-conformance
  labels:
    app: verify-conformance
spec:
  schedule: '*/2 * * * *'
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: verify-conformance
      labels:
        app: verify-conformance
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: OnFailure
          containers:
            - name: verify-conformance
              image: ko://sigs.k8s.io/verify-conformance
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
                privileged: false
              args:
                - --github-endpoint=http://ghproxy.prow
                - --github-endpoint=https://api.github.com
                - --dry-run=false
                - --hmac-secret-file=/etc/webhook/hmac
                - --github-app-id=$(GITHUB_APP_ID)
                - --github-app-private-key-path=/etc/github/cert
                - --repo=cncf/k8s-conformance
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: appid
              ports:
                - name: http
                  containerPort: 8888
              volumeMounts:
                - name: hmac
                  mountPath: /etc/webhook
                  readOnly: true
                - name: oauth
                  mountPath: /etc/github
                  readOnly: true
          volumes:
            - name: hmac
              secret:
                secretName: hmac-token
            - name: oauth
              secret:
                secretName: github-token
