---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verify-conformance
  labels:
    app: verify-conformance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verify-conformance
  template:
    metadata:
      labels:
        app: verify-conformance
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: verify-conformance
          image: ko://sigs.k8s.io/verify-conformance
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            privileged: false
          args:
            - --github-endpoint=http://ghproxy.prow
            - --github-endpoint=https://api.github.com
            - --dry-run=false
            - --hmac-secret-file=/etc/webhook/hmac
            - --plugin-config=/plugin/verify-conformance-config.yaml
            - --update-period=5m
            - --github-app-id=$(GITHUB_APP_ID)
            - --github-app-private-key-path=/etc/github/cert
          env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: appid
          ports:
            - name: http
              containerPort: 8888
          volumeMounts:
            - name: hmac
              mountPath: /etc/webhook
              readOnly: true
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: plugins
              mountPath: /etc/plugins
              readOnly: true
            - name: verify-conformance-config
              mountPath: /plugin/verify-conformance-config.yaml
              subPath: verify-conformance-config.yaml
              readOnly: true
      volumes:
        - name: hmac
          secret:
            secretName: hmac-token
        - name: oauth
          secret:
            secretName: github-token
        - name: plugins
          configMap:
            name: plugins
        - name: verify-conformance-config
          configMap:
            name: verify-conformance-config
