apiVersion: v1
kind: ConfigMap
metadata:
  name: vcr-config
  namespace: prow
data:
  vcr.yaml: |
    external_plugins:
      cncf/k8s-conformance:
      - name: verify-conformance-release
        events:
          - issue_comment
          - pull_request

      cncf-infra/k8s-conformance:
      - name: verify-conformance-release
        events:
          - issue_comment
          - pull_request
