apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespaces.yaml
- ../../config/default
- ./ghproxy.yaml
patches:
- path: ./verify-conformance-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - ./plugins.yaml
  name: plugins
  namespace: verify-conformance
- files:
  - localRegistryHosting.v1=./local-registry-hosting.yaml
  name: local-registry-hosting
  namespace: kube-public
secretGenerator:
- files:
  - token=./tmp/token
  name: github-token
  namespace: verify-conformance
- files:
  - hmac=./tmp/hmac
  name: hmac-token
  namespace: verify-conformance
images:
- digest: sha256:2a3282841346c2721ee309b8f0c73969447afab5bda64c570b699ba9cca26a43
  name: ko://sigs.k8s.io/verify-conformance
  newName: localhost:5001/verify-conformance/verify-conformance
