apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespaces.yaml
- ../../config/default
- ./ghproxy.yaml
patches:
- path: ./verify-conformance-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- behavior: replace
  files:
  - ./verify-conformance-config.yaml
  name: verify-conformance-config
  namespace: verify-conformance
- files:
  - ./plugins.yaml
  name: plugins
  namespace: verify-conformance
- files:
  - localRegistryHosting.v1=./local-registry-hosting.yaml
  name: local-registry-hosting
  namespace: kube-public
secretGenerator:
- files:
  - token=./tmp/token
  name: github-token
  namespace: verify-conformance
- files:
  - hmac=./tmp/hmac
  name: hmac-token
  namespace: verify-conformance
images:
- name: ko://sigs.k8s.io/verify-conformance
  newTag: latest
  newName: localhost:5001/verify-conformance/verify-conformance
