---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: verify-conformance
  namespace: verify-conformance
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: verify-conformance
      labels:
        app: verify-conformance
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: verify-conformance
              args:
                - --github-endpoint=http://ghproxy.prow
                - --github-endpoint=https://api.github.com
                - --dry-run=false
                - --hmac-secret-file=/etc/webhook/hmac
                - --update-period=5m
                - --github-token-path=/etc/github/token
                - --repo=cncf-infra/k8s-conformance
              env:
