name: Image build

on:
  push:
    paths:
      - internal/**
      - kodata/**
      - pkg/**
      - .ko.yaml
      - go.mod
      - go.sum
      - .github/workflows/build.yml

  # Run tests for any PRs.
  # pull_request:

jobs:
  push_verify_release:
    # Ensure test job passes before pushing image.
    # needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.3"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::928655657136:role/verify-conformance-ci
      - name: get kubeconfig
        run: |
          aws eks list-clusters \
            --region ap-southeast-2
          aws eks \
            update-kubeconfig \
            --region ap-southeast-2 \
            --name prow-cncf-io-eks
      - uses: imjasonh/setup-ko@v0.6
      - name: Build push verify-conformance-release image to GHCR
        env:
          REGISTRY: ghcr.io/cncf-infra/verify-conformance
        run: |
          set -x
          IMAGE_ID=$(echo $REGISTRY | tr '[A-Z]' '[a-z]')
          export KO_DOCKER_REPO="${IMAGE_ID}"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ -n "${VERSION:-}" ] && [ ! "${VERSION:-}" = "${{ github.event.repository.default_branch }}" ]; then
            BRANCH="-${VERSION:-}"
          fi
          ko apply \
            --bare \
            --push \
            --platform linux/amd64,linux/arm64,linux/arm64/v8 \
            --tags "latest${BRANCH:-},${{ steps.slug.outputs.sha8 }}" \
            -f ./manifests/ \
            .
      - name: watch rollout
        run: |
          kubectl -n prow rollout status deployment verify-conformance-release
          kubectl -n prow get pod -l app=verify-conformance-release
