name: code quality check
on:
  push:
    branches:
      - '!main'
  pull_request: {}
  workflow_dispatch: {}
jobs:
  gobuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gobuild
        id: gobuild
        run: ./hack/verify-gobuild.sh
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gofmt
        id: gofmt
        run: ./hack/verify-gofmt.sh
  goimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: goimports
        id: goimports
        run: ./hack/verify-goimports.sh
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
      - name: write .golangci.yml
        if: ${{ inputs.config }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: v1.55.2
          args: --timeout 10m
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: golint
        id: golint
        run: ./hack/verify-golint.sh
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gotest
        id: gotest
        run: ./hack/verify-gotest.sh
  govet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: govet
        id: govet
        run: ./hack/verify-govet.sh
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: govulncheck
        id: govulncheck
        run: ./hack/verify-govulncheck.sh
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: spellcheck
        id: spellcheck
        run: ./hack/verify-spellcheck.sh
