name: code quality check

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: gofmt
        id: gofmt
        run: find . -name "*.go" | grep -E -v vendor | xargs gofmt -s -l -d -e
      - name: check-gofmt
        if: ${{ steps.gofmt.outputs.stdout != '' }}
        run: |
          echo "gofmt discovered regions requiring formatting"
          exit 1
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
      - name: write .golangci.yml
        if: ${{ inputs.config }}
        run: |
          echo "Using config:"
          echo '${{ inputs.config }}' | tee .golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.55.2
          args: --timeout 10m
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: test
        id: test
        run: go test -v ./... -cover
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - name: vet
        id: vet
        run: go vet -v ./...
