name: publish
on:
  workflow_dispatch: {}
  release:
    types: [published]
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - id: run-info
        name: collect job run info
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        run: |
          echo "ko-docker-repo=${KO_DOCKER_REPO,,}" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: go.sum
      - uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
      - uses: ko-build/setup-ko@3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037 # v0.7
      - name: build
        env:
          CI_COMMIT_TAG: ${{ github.event.release.name }}
          KO_DOCKER_REPO: ${{ steps.run-info.outputs.ko-docker-repo }}
        run: ./hack/publish.sh --sign
