name: reusable gofmt
on:
  workflow_call: {}
jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - id: run-info
        name: collect job run info
        run: |
          echo "go-version=$(go list -f {{.GoVersion}} -m)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ steps.run-info.outputs.go-version }}
          cache-dependency-path: go.sum
      - name: gofmt
        id: gofmt
        run: find . -name "*.go" | grep -E -v vendor | xargs gofmt -s -l -d -e
      - name: check-gofmt
        if: ${{ steps.gofmt.outputs.stdout != '' }}
        run: |
          echo "gofmt discovered regions requiring formatting"
          exit 1
