name: update go version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-go-version:
    uses: cncf-infra/verify-conformance/.github/workflows/reusable-update-go-version.yml@main
    with:
      autoMerge: true
